name: sth
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  http: ^1.1.0
  rxdart: ^0.27.7
  carousel_slider: ^4.2.1

  youtube_player_flutter: ^8.1.2
  url_launcher: ^6.2.1
  # simple_share: ^0.0.1+4 
  shared_preferences: ^2.2.2
  pref_dessert: ^0.8.0 
  sqflite: any
  path_provider: ^2.1.1
  country_pickers: ^2.0.0
  shimmer: ^3.0.0
  # firebase_admob: ^0.9.3+1
  connectivity_plus: ^5.0.1
  provider: ^6.1.1
  grouped_list: ^5.1.2
  # flutter_speed_dial_material_design: ^2.0.0
  drag_and_drop_lists: ^0.3.3
  webview_flutter: ^4.4.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  dio: ^5.3.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  cached_network_image: ^3.3.0
  freezed_annotation: ^2.4.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.5

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/sports.json
   - assets/images/

